# Cloud Build configuration para entrenar modelo en GCP
# Uso: gcloud builds submit --config=cloudbuild.yaml

steps:
  # Paso 1: Instalar dependencias
  - name: 'python:3.11'
    id: 'install-dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Instalando dependencias..."
        pip install -r requirements.txt

  # Paso 2: Entrenar modelo de churn
  - name: 'python:3.11'
    id: 'train-churn-model'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Iniciando entrenamiento del modelo..."
        pip install -r requirements.txt
        python train_churn_prediction.py
        echo "✅ Modelo entrenado exitosamente"

  # Paso 3: Subir modelo a Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-to-gcs'
    args:
      - 'cp'
      - '-r'
      - 'churn_model/'
      - 'gs://${_BUCKET_NAME}/churn_model/'

# Opciones de build
options:
  machineType: 'E2_HIGHCPU_8'  # 8 vCPUs para entrenamiento más rápido
  diskSizeGb: 50
  logging: CLOUD_LOGGING_ONLY

# Variables sustituibles
substitutions:
  _BUCKET_NAME: 'churnito-models'  # Cambiar por tu bucket

# Timeout de 30 minutos (el entrenamiento puede tardar)
timeout: 1800s
